### PR TITLE
🐛 Fix: Disconnect sidenote issue

### PR DESCRIPTION
**Pull request by ghanshyam-1805**
The sidenote disconnect issue has been solved by adding UI_DISCONNECT_SIDENOTE into the reducer.

### CODE REVIEW

**Comment by ronak2898** [comment]
Yes, I also face this issue. Thanks! 🤠

**Comment by ghanshyam-1805** [comment]
@rowanc1 Any Update?

**Comment by rowanc1** [comment]
Thanks for the ping. Looks good from my phone. Will aim to get a release out tomorrow.

**Comment by rowanc1** [comment]
This has been deployed as 1.0.6, sorry that took so long to respond!

**Comment by ghanshyam-1805** [comment]
> This has been deployed as 1.0.6, sorry that took so long to respond!

Okay, Thanks!

**Pull request merged**
